apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  namespace: default
  name: criar-s3-v1
  title: Criação de Buckets no Amazon S3
  description: >
    O Amazon S3, ou Simple Storage Service, é um serviço de armazenamento em nuvem oferecido pela Amazon Web Services (AWS). Ele permite armazenar e recuperar grandes quantidades de dados de forma segura, escalável e altamente disponível. O S3 é frequentemente utilizado para hospedar sites estáticos, armazenar backups, distribuir conteúdo e muito mais. Para criar um novo recurso no Amazon S3, é necessário primeiro acessar o console da AWS e navegar até o serviço S3. Em seguida, clique em "Criar bucket" para iniciar o processo. Um "bucket" é o nome dado ao contêiner de armazenamento principal no S3, que é usado para organizar e gerenciar os arquivos. Durante a criação, você precisará fornecer um nome único para o bucket, escolher a região onde ele será hospedado e configurar as permissões de acesso. Após a criação bem-sucedida, você estará pronto para começar a enviar e gerenciar seus dados no Amazon S3.
  labels:
    example.com/custom: custom_label_value
  annotations:
    example.com/service-discovery: teste
    circleci.com/project-slug: github/pocacc/aws-s3-tf
  tags:
    - storage
    - bucket
    - resource
    - devops
  links:
    - url: https://backstage.iccloudstudio.com/
      title: Accenture
      icon: dashboard
      type: admin-dashboard
spec:
  owner: group:infrastructure
  type: resource

  parameters:
  - title: Informacões sobre o solicitante
    required:
      - nome
      - email
    properties:
      nome:
        title: Nome do líder técnico da área*
        type: string
        description: Insira o nome do líder técnico.
        ui:autofocus: true
      email:
        title: E-mail do líder técnico*
        type: string
        description: Insira o nome do líder técnico.
        ui:autofocus: true

  - title: Selecione o ambiente AWS
    properties:
      environment:
        title: Selecione o ambiente
        type: string
        default: development
        enum:
          - prd
          - stg
          - dev
        enumNames:
          - production
          - staging
          - development
      region:
        title: Escolha a região
        type: string
        description: Região na AWS a qual o ambiente será configurado
        default: us-east-1
        enum:
          - af-south-1
          - ap-east-1
          - ap-south-1
          - ap-northeast-3
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-2
          - ap-northeast-1
          - ca-central-1
          - eu-central-1
          - eu-west-1
          - eu-west-2
          - eu-south-1
          - eu-west-3
          - eu-north-1
          - sa-east-1
          - us-gov-west-1
          - us-east-1
          - us-east-2
          - us-west-1
          - us-west-2
        enumNames:
          - África (Cidade do Cabo) - af-south-1
          - Ásia-Pacífico (Hong Kong) - ap-east-1
          - Ásia-Pacífico (Mumbai) - ap-south-1
          - Ásia-Pacífico (Osaka-Local) - ap-northeast-3
          - Ásia-Pacífico (Seoul) - ap-northeast-2
          - Ásia-Pacífico (Cingapura) - ap-southeast-1
          - Ásia-Pacífico (Sydney) - ap-southeast-2
          - Ásia-Pacífico (Tóquio) - ap-northeast-1
          - Canadá (Central) - ca-central-1
          - Europa (Frankfurt) - eu-central-1
          - Europa (Irlanda) - eu-west-1
          - Europa (Londres) - eu-west-2
          - Europa (Milão) - eu-south-1
          - Europa (Paris) - eu-west-3
          - Europa (Estocolmo) - eu-north-1
          - América do Sul (São Paulo) - sa-east-1
          - AWS GovCloud (EUA) - us-gov-west-1
          - Leste dos EUA (Norte da Virgínia) - us-east-1
          - Leste dos EUA (Ohio) - us-east-2
          - Oeste dos EUA (Norte da Califórnia) - us-west-1
          - Oeste dos EUA (Oregon) - us-west-2
  - title: Defina as configurações do ambiente
    properties:
      bucket:
        title: Nome do bucket
        type: string
        description: O nome do bucket é único e global
        ui:autofocus: true
      force_destroy:
        title: Force destroy
        type: string
        description: O Bucket poderá ser destruído mesmo com arquivos?
        default: "false"
        enum:
          - "false"
          - "true"
        enumNames:
          - "Não"
          - "Sim"
      acl:
        title: Defina o ACL do bucket
        type: string
        description: O bucket terá acesso público ou privado?
        default: "private"
        enum:
          - "private" 
          - "public-read"
          - "public-read-write"
          - "authenticated-read"
          - "aws-exec-read"
          - "log-delivery-write"
        enumNames:
          - "privado"
          - "público leitura"
          - "público leitura e escrita"
          - "autenticação leitura"
          - "aws execução e leitura"
          - "entrega e escrita de log"
  steps:
    - id: step2
      name: Log message
      action: debug:log
    - id: BackendTF
      name: Terraform backend configuration
      action: fetch:template
      input:
        url: ./backend.tf
        values:
          bucket: "\"${{  parameters.bucket }}\""
          environment: "\"${{ parameters.environment }}\""
    - id: Global Variables
      name: Template S3 Terraform
      action: fetch:template
      input:
        url: .
        values:
          email: "\"${{ parameters.email }}\""
          bucket: "\"${{  parameters.bucket }}\""
          force_destroy: "\"${{  parameters.force_destroy }}\""
          acl: "\"${{  parameters.acl }}\""
          region: "\"${{  parameters.region }}\""
          role_to_assume : "\"arn:aws:iam::859860534726:role/ic-openid-connect-git-role\""
          role_session_name: "\"ic-telefonica-openid-role\""
          environment: "\"${{ parameters.environment }}\""
    - id: GitHubAction
      name: Insert Variables GitHub Action
      action: fetch:template
      input:
        url: ./.github/workflows/backstage_deploy.yml
        values:
          resource: ${{ parameters.bucket }}
          bucket: "\"${{  parameters.bucket }}\""
          region: ${{ parameters.region }}
          role_to_assume : arn:aws:iam::859860534726:role/ic-openid-connect-git-role
          role_session_name: ic-telefonica-openid-role
          environment: "\"${{ parameters.environment }}\""
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts:
          - github.com
        description: This is ${{ parameters.bucket }}
        repoUrl: github.com?owner=pocacc&repo=${{ parameters.bucket }}
        RepoVisibility: public
        branchName: main

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
